<footer>
        <p>Web development &copy; 2025 Arturo Mora-Rioja</p>
        <section id="others">
            <p>
                Homepage picture by <a 
                    href="https://www.pexels.com/@weekendplayer/" 
                    title="Burak The Weekender" 
                    target="_blank">Burak The Weekender</a> at <a 
                href="https://www.pexels.com/" 
                title="Pexels" target="_blank">Pexels</a>
            </p>
            <p>Homepage text generated by <a href="https://chatgpt.com/" 
                title="ChatGPT" 
                target="_blank">ChatGPT</a></p>
        </section>
    </footer>
</body>
</html>